name: Build and Deploy
on: [push]
jobs:
   build-and-deploy:
      runs-on: ubuntu-latest
      steps:
         - name: Checkout
           uses: actions/checkout@master

         - name: vuepress-deploy
           uses: jenkey2011/vuepress-deploy@master
           env:
              ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
              TARGET_REPO: riasuh/webproject
              TARGET_BRANCH: main
              BUILD_SCRIPT: yarn install && yarn run docs:build
              BUILD_DIR: docs/.vuepress/dist
              CNAME:
